import sqlite3

# Initialize SQLite database
conn = sqlite3.connect("supabase.db")

c = conn.cursor()


# Create transactions table if it doesn't exist
c.execute("""
    CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL,
    type TEXT NOT NULL,
    date DATE NOT NULL,
    ex_in TEXT NOT NULL,
    description TEXT
);
""")

# Create type_colors table if it doesn't exist
c.execute("""
    CREATE TABLE type_colors (
    type TEXT PRIMARY KEY,
    color TEXT NOT NULL
);
""")

# add default colors for the types
default_colors = {
    "Salary": "#20FC8F",
    "Groceries": "#FF6B6C",
    "Rent": "#FFC145",
    "Entertainment": "#5B5F97",
    "Travel": "#FF6F91",
    "Mobility": "#6A0572"
    # ,"Other": "#B8B8D1"
}
for t, color in default_colors.items(): 
    c.execute("INSERT OR IGNORE INTO type_colors (Type, color) VALUES (:type, :color)", {"type": t, "color": color})
    conn.commit()

# create budgets table if it doesn't exist
c.execute("""
    CREATE TABLE budgets (
    type TEXT PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL
);
""")
    